baseURL: https://dexterowski.github.io/
title: DX PUZZLES 2024
theme: hugo-theme-bootstrap
copyright: 'Copyright © 2024 - DX STUDIO'
defaultContentLanguage: en
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true

useHLJS: true

markup:
  highlight:
    codeFences: true
    useChroma: false
    noClasses: false
    style: native
    tabWidth: 4
    lineNos: false



markup:
  goldmark:
    renderer:
      unsafe: true

pygmentsCodeFences: false
pygmentsUseClasses: false
pygmentsStyle: monokai

params:
  highlightjs: true
  highlightjsTheme: monokai


blackfriday:
  hrefTargetBlank: true

#taxonomies:
 # category: categories
 # series: series
  #tag: tags
 # authors: authors



build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/


# module:
  # proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

module:
  imports:
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/font-awesome
  - path: github.com/hugomods/bootstrap



