#main:
#  - name: Documentations
#    identifier: documentations
#    url: https://hbs.razonyang.com/v1/en/docs/
#    params:
#      icon: '<i class="fas fa-fw fa-book"></i>'


main:
  - name: Developer Docs
    url: /docs/
    params:
      icon: '<i class="fas fa-fw fa-book"></i>'